title: "tnkr.xyz"
author: "Max Perrello"
twitter: "MaxPerrello"
description: "a hub for all my dumb projects, in various stages of completion"
banner: "https://www.solidbackgrounds.com/images/950x350/950x350-midnight-green-solid-color-background.jpg"
logo: "img/favicon-32x32.png"
analytics: "UA-125984204-6"
exclude:
  - README.md
